# Generated by Django 4.1.2 on 2022-10-21 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadastroDentistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('diabetico', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('hipertenso', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('alergia_a_medicamentos', models.CharField(default='não', max_length=100)),
                ('outras_observacoes', models.CharField(blank=True, default='não', max_length=200, verbose_name='Observações')),
                ('historico', models.TextField(max_length=3000)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CadastroDentistas.dentista')),
            ],
        ),
    ]
