# Generated by Django 4.1.2 on 2022-10-21 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Especialidade',
            },
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('CRO', models.CharField(max_length=7)),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CadastroDentistas.especialidades')),
            ],
        ),
    ]
